# Test
this is a test file.

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_csv("songs.csv")
a

曲名  调性                                                 乐谱
0           水星记   F  [[6,0,5,0,3,0,6,0,0,0,5,0,3,0,6,0],[0,0,0,0,0,...
1         最美的期待   C  [[0,0,0,1,1,7,1,2,0,0,0,2,2,1,7,1],[0,6,0,1,1,...
2         最美的期待   C  [[0,0,0,1,1,2,3,5,0,2,0,2,2,1,7,1],[0,6,0,2,2,...
3            稻香   A  [[1,0,6,1,0,1,1,1,2,2,2,2,3,0,1,0],[1,0,6,1,0,...
4            稻香   A  [[5,0,5,5,0,5,5,5,0,5,5,5,3,0,2,0],[1,0,2,3,0,...
..          ...  ..                                                ...
126    Who Says  #D  [[3,0,5,0,4,3,2,1,3,0,5,0,4,3,2,1],[3,0,5,0,4,...
127    The Show   C  [[3,0,3,2,3,2,3,2,3,0,3,2,3,5,0,2],[0,0,2,1,2,...
128      Domino   G  [[0,0,5,0,0,5,0,5,0,4,4,3,2,0,3,0],[0,0,3,0,0,...
129  This is me   D  [[6,0,5,5,0,0,3,3,3,0,5,3,0,2,1,0],[0,0,0,0,0,...
130       在你的身边   G  [[0,5,5,3,2,1,6,1,0,0,0,1,1,1,5,5],[0,5,5,3,2,...

[131 rows x 3 columns]

In [3]:
a["乐谱"][2]

'[[0,0,0,1,1,2,3,5,0,2,0,2,2,1,7,1],[0,6,0,2,2,1,7,1,0,5,0,1,1,2,3,5],[0,0,0,1,1,7,6,6,0,5,0,4,4,3,2,3],[0,0,0,1,4,3,2,4,0,1,0,1,0,2,0,1]]'

In [4]:
strings = eval(a["乐谱"][7])
strings

[[5, 0, 1, 0, 3, 0, 0, 3, 2, 0, 1, 0, 3, 0, 0, 0],
 [2, 0, 1, 0, 2, 0, 0, 3, 2, 0, 1, 0, 6, 0, 0, 0],
 [6, 0, 1, 0, 2, 0, 0, 3, 2, 0, 1, 0, 6, 0, 0, 0],
 [5, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [5]:
puzi = np.array(strings, dtype=float)
puzi

array([[5., 0., 1., 0., 3., 0., 0., 3., 2., 0., 1., 0., 3., 0., 0., 0.],
       [2., 0., 1., 0., 2., 0., 0., 3., 2., 0., 1., 0., 6., 0., 0., 0.],
       [6., 0., 1., 0., 2., 0., 0., 3., 2., 0., 1., 0., 6., 0., 0., 0.],
       [5., 6., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
# from real number to songs
change_dict = {0:1009, 1:60, 1.5:61, 2:62, 2.5:63, 3:64, 4:65, 4.5:66, 5:67,
               5.5:68, 6:69, 6.5:70, 7:71}

In [7]:
input = a["乐谱"]
input

0      [[6,0,5,0,3,0,6,0,0,0,5,0,3,0,6,0],[0,0,0,0,0,...
1      [[0,0,0,1,1,7,1,2,0,0,0,2,2,1,7,1],[0,6,0,1,1,...
2      [[0,0,0,1,1,2,3,5,0,2,0,2,2,1,7,1],[0,6,0,2,2,...
3      [[1,0,6,1,0,1,1,1,2,2,2,2,3,0,1,0],[1,0,6,1,0,...
4      [[5,0,5,5,0,5,5,5,0,5,5,5,3,0,2,0],[1,0,2,3,0,...
                             ...                        
126    [[3,0,5,0,4,3,2,1,3,0,5,0,4,3,2,1],[3,0,5,0,4,...
127    [[3,0,3,2,3,2,3,2,3,0,3,2,3,5,0,2],[0,0,2,1,2,...
128    [[0,0,5,0,0,5,0,5,0,4,4,3,2,0,3,0],[0,0,3,0,0,...
129    [[6,0,5,5,0,0,3,3,3,0,5,3,0,2,1,0],[0,0,0,0,0,...
130    [[0,5,5,3,2,1,6,1,0,0,0,1,1,1,5,5],[0,5,5,3,2,...
Name: 乐谱, Length: 131, dtype: object

In [8]:
def my_eval(x):
    return np.array(eval(x))

In [9]:
input_to_numpy = input.apply(my_eval).to_numpy()
input_to_numpy

array([array([[6, 0, 5, 0, 3, 0, 6, 0, 0, 0, 5, 0, 3, 0, 6, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 5, 0, 1, 0, 3, 0],
              [0, 0, 2, 0, 5, 0, 3, 0, 0, 0, 2, 0, 5, 0, 3, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 5, 0]]),
       array([[0, 0, 0, 1, 1, 7, 1, 2, 0, 0, 0, 2, 2, 1, 7, 1],
              [0, 6, 0, 1, 1, 7, 1, 2, 0, 1, 0, 3, 0, 2, 0, 1],
              [0, 0, 0, 1, 1, 7, 1, 2, 0, 0, 0, 2, 2, 1, 7, 1],
              [0, 6, 0, 1, 1, 7, 1, 2, 0, 1, 0, 3, 0, 2, 0, 1]]),
       array([[0, 0, 0, 1, 1, 2, 3, 5, 0, 2, 0, 2, 2, 1, 7, 1],
              [0, 6, 0, 2, 2, 1, 7, 1, 0, 5, 0, 1, 1, 2, 3, 5],
              [0, 0, 0, 1, 1, 7, 6, 6, 0, 5, 0, 4, 4, 3, 2, 3],
              [0, 0, 0, 1, 4, 3, 2, 4, 0, 1, 0, 1, 0, 2, 0, 1]]),
       array([[1, 0, 6, 1, 0, 1, 1, 1, 2, 2, 2, 2, 3, 0, 1, 0],
              [1, 0, 6, 1, 0, 0, 1, 1, 2, 2, 2, 2, 3, 0, 1, 0],
              [1, 0, 6, 1, 0, 0, 1, 1, 2, 2, 2, 2, 0, 0, 1, 0],
              [3, 0, 0, 0, 0, 0, 0

In [10]:
def my_concatenate(x):
    return np.concatenate(x)

In [11]:
input_to_numpy = np.vectorize(my_concatenate)(input_to_numpy)
input_to_numpy

ValueError: setting an array element with a sequence.